services:
  - type: web
    name: volleyball-coach
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd volleyball-coach && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000 